name: Build Generation

on:
  workflow_dispatch:
    inputs:

      variant:
        description: 'Build Variant'
        required: true
        default: 'NyUserProdDebug'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:

      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update local.properties 
        env:
          MOBILITY_SERVICES: ${{ secrets.MOBILITY_SERVICES }}
          MASTER_APP_CONFIG: ${{ secrets.MASTER_APP_CONFIG }}
        run: |
           bash android-native/update_properties.sh "$MOBILITY_SERVICES" "$MASTER_APP_CONFIG" ${{ github.event.inputs.variant }}
           bash android-native/apk_path.sh ${{ github.event.inputs.variant }}
           
      
      - name: Read path from file
        run: |
          apk_path=$(cat path.txt)
          echo "apk_path=$apk_path" >> "$GITHUB_OUTPUT"
        id: set_apk_path

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      - name: Build APK
        run: |
          echo "APK Path 2: ${{ github.event.inputs.variant }}"
          cd android-native  # Adjust the path as needed
          bash github_apk_build.sh ${{ github.event.inputs.variant }}

      

      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.variant }}
          path: ${{ steps.set_apk_path.outputs.apk_path }}
