name: Docker Image CI

on:
  push:
    branches: ["main", "sandbox", "production"]
    paths:
      - 'Backend/**'

env:
  DEP_IMAGE: nammayatri-dep
  IMAGE_NAME: nammayatri
  DEP_LABEL: ${{github.ref_name}}
  REGISTRY: ghcr.io
  REPO_NAME: nammayatri

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checking for free space
        run: |
          echo "Free space: Before "
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "Free space: After "
          df -h
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: set up env var version
        run: echo "VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Adding Path filters
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dockerFilePath:
              - '**/Dockerfile*'
            stackPath:
              - '**/stack.yaml'
            stackLockPath:
              - '**/stack.yaml.lock'
            packagePath:
              - '**/package.yaml'
      - name: Build DockerDep image
        if: steps.filter.outputs.dockerFilePath == 'true' || steps.filter.outputs.stackPath == 'true' || steps.filter.outputs.stackLockPath == 'true' || steps.filter.outputs.packagePath == 'true'
        run: docker build -t $REGISTRY/$REPO_NAME/$DEP_IMAGE:$DEP_LABEL -f Backend/Dockerfile.dep .
      - name: DockerDep Image Push
        if: steps.filter.outputs.dockerFilePath == 'true' || steps.filter.outputs.stackPath == 'true' || steps.filter.outputs.stackLockPath == 'true' || steps.filter.outputs.packagePath == 'true'
        run: docker push $REGISTRY/$REPO_NAME/$DEP_IMAGE:$DEP_LABEL
      - name: Build the Docker image
        run: docker build -t $REGISTRY/$REPO_NAME/$IMAGE_NAME:$VERSION -f Backend/Dockerfile --build-arg "DEP_LABEL=$DEP_LABEL" --build-arg "DEP_IMAGE_PATH=$REGISTRY/$REPO_NAME/$DEP_IMAGE" .
      - name: Docker Push
        run: docker push $REGISTRY/$REPO_NAME/$IMAGE_NAME:$VERSION
