name: Compress Lottie Files
on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

jobs:
  compress-lottie:
    name: Compress Lottie JSON Files
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Ensure jq is installed
      - name: Install jq
        run: sudo apt-get install jq

      - name: Run pwd
        run: pwd

      # Extract commit range from the pull request
      - name: Set Commit Range
        id: commit-range
        run: echo "range=$(echo "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}")" >> $GITHUB_ENV

      # Run the compression script for files in the commit range
      - name: Compress Changed Lottie Files
        run: |
          chmod +x ./compress_lottie.sh
          ./compress_lottie.sh "$range"

      # Commit and push the compressed files if there are any changes
      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[github-bot] Compressed Lottie JSON files" || echo "No changes to commit"
          git push
