name: Execute Script

on: [push, pull_request]

jobs:
  on_pr_merge:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Test changed-files
        uses: actions/checkout@v4
    
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44   

      - name: Fetch User Name and Email
        run: |
          username=$(git log -1 --pretty=format:"%an")
          email=$(git log -1 --pretty=format:"%ae")
          echo "User name: $username"
          echo "User email: $email" 

      - name: Clone asset-store repo 
        run: |
          username=$(git log -1 --pretty=format:"%an")
          email=$(git log -1 --pretty=format:"%ae")
          git config --global user.email "$email"
          git config --global user.name "$username"
          git clone "git@github.com:$username/MercyQueen/asset-store.git" asset-store
        env : 
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Run script
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          chmod +x asset-store-script.sh 
          ./asset-store-script.sh ${{ github.event.pull_request.head.ref }} ${{ secrets.GITHUB_TOKEN }}
